#!/bin/bash
echo "The School is open and might be closed"
Lets try again
echo "The School is open and closed. Thank you"
echo "The School is open. Leave me"
Lets try again
echo "The School is open and closed. Hi"
We did it again
